server:
  port: 8001
  servlet:
    context-path: "/provider"

spring:
  application:
    name: provider-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/
    registry-fetch-interval-seconds: 30 #30秒刷新缓存
  instance:
    instance-id: provider8001
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
